### ISSUE TITLE
Projects page SyntaxError in Firefox for lambda function response

### ISSUE THREAD

**Issue by rokeby** [agnescameron/foreignobjects#11]
/projects works fine in Safari and Chrome but in Firefox, projects don't populate from Airtable:

`SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"`

and fails to print response.json in console

**Comment by Kallirroi** [comment]
Sounds like a response parsing error, maybe you can experiment with JSON methods parse() and stringify() ? Here's a link: https://attacomsian.com/blog/json-parse-stringify . Not sure why only Firefox would have that problem though...
